import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { YODA_VERSION, type InitAnswersV1 } from "@mestre-yoda/contracts";
import { createSchemaRegistry } from "@mestre-yoda/runtime/composition/schema";
import type { Effect } from "@mestre-yoda/runtime/domain/effects";
import {
  MANAGED_SECTION_BEGIN,
  MANAGED_SECTION_END,
  destinationsOf,
  profileStack,
  skeletonEffects,
} from "@mestre-yoda/runtime/domain/init";
import { beforeAll, describe, expect, it, vi } from "vitest";

const discoveryPath = join(
  fileURLToPath(new URL("../", import.meta.url)),
  "compatibility/inventory/go-v3-v0.6.5/discovery.json",
);

interface Discovery {
  readonly namespaces: {
    readonly generated_files: readonly { readonly name: string }[];
  };
}

/**
 * The frozen surface, read from the oracle rather than retyped.
 *
 * A path that drifts from the inventory fails here instead of shipping.
 */
let frozen: readonly string[];

beforeAll(async () => {
  const discovery = JSON.parse(
    await readFile(discoveryPath, "utf8"),
  ) as Discovery;
  frozen = discovery.namespaces.generated_files
    .map(({ name }) => name)
    // A path carrying a feature or a run segment belongs to the command that
    // owns that lifecycle, not to initialization.
    .filter((name) => !name.includes("<"))
    .sort();
});

const registry = createSchemaRegistry();
const nodeProject = profileStack({ rootEntries: ["package.json"] });

function answers(
  overrides: Partial<Required<InitAnswersV1>> = {},
): Required<InitAnswersV1> {
  return {
    contractVersion: "1.0.0",
    hostContract: "1.0.0",
    hosts: ["claude", "codex"],
    language: "en",
    policyMode: "standard",
    snapshots: true,
    ...overrides,
  };
}

function contentAt(effects: readonly Effect[], path: string): string {
  const effect = effects.find(
    (candidate) => candidate.kind === "write_file" && candidate.path === path,
  );
  if (effect?.kind !== "write_file") {
    throw new Error(`nothing was generated at ${path}`);
  }
  return effect.content;
}

function underBrain(path: string): boolean {
  return path.startsWith(".brain/");
}

describe("the generated skeleton", () => {
  it("generates exactly the frozen initialization surface", () => {
    expect(destinationsOf(skeletonEffects(answers(), nodeProject))).toEqual(
      frozen,
    );
  });

  it("writes files and creates no directory of its own", () => {
    // The transaction normalizer synthesizes missing parents. A
    // create_directory effect here would be a second, divergent opinion about
    // which directories exist.
    const kinds = skeletonEffects(answers(), nodeProject).map(
      ({ kind }) => kind,
    );

    expect([...new Set(kinds)]).toEqual(["write_file"]);
  });

  it("produces byte-identical effects for identical inputs", () => {
    expect(skeletonEffects(answers(), nodeProject)).toEqual(
      skeletonEffects(answers(), nodeProject),
    );
  });

  it("does not let the host order reach a generated byte", () => {
    // Iteration order is the classic way a second run rewrites files that were
    // already right.
    expect(
      skeletonEffects(answers({ hosts: ["codex", "claude"] }), nodeProject),
    ).toEqual(
      skeletonEffects(answers({ hosts: ["claude", "codex"] }), nodeProject),
    );
  });

  it("reaches no clock, no random source, and no identifier generator", () => {
    const refuse = (name: string) => (): never => {
      throw new Error(`generation reached ${name}`);
    };
    // Sealing the constructor as well as `now` closes `new Date()`, which is
    // the reading of the clock a generator is most likely to make by accident.
    const sealedClock = refuse("the clock");
    vi.stubGlobal("Date", Object.assign(sealedClock, { now: sealedClock }));
    const random = vi
      .spyOn(Math, "random")
      .mockImplementation(refuse("Math.random"));
    const uuid = vi
      .spyOn(globalThis.crypto, "randomUUID")
      .mockImplementation(refuse("crypto.randomUUID"));

    let generated: readonly Effect[];
    try {
      generated = skeletonEffects(answers(), nodeProject);
    } finally {
      vi.unstubAllGlobals();
      random.mockRestore();
      uuid.mockRestore();
    }

    expect(destinationsOf(generated)).toEqual(frozen);
  });

  it("generates only the surface of the hosts the answers enabled", () => {
    const claudeOnly = destinationsOf(
      skeletonEffects(answers({ hosts: ["claude"] }), nodeProject),
    );
    const codexOnly = destinationsOf(
      skeletonEffects(answers({ hosts: ["codex"] }), nodeProject),
    );

    expect(claudeOnly).toEqual(
      frozen.filter(
        (path) => !path.startsWith(".codex/") && path !== "AGENTS.md",
      ),
    );
    expect(codexOnly).toEqual(
      frozen.filter(
        (path) => !path.startsWith(".claude/") && path !== "CLAUDE.md",
      ),
    );
    // State is not a host's property: the `.brain` skeleton is the same either
    // way.
    expect(claudeOnly.filter(underBrain)).toEqual(codexOnly.filter(underBrain));
  });

  it("writes a project configuration the runtime itself accepts", () => {
    const generated = skeletonEffects(
      answers({ language: "pt-BR", policyMode: "strict", snapshots: false }),
      nodeProject,
    );
    const config: unknown = JSON.parse(
      contentAt(generated, ".brain/config.json"),
    );

    expect(config).toEqual({
      contractVersion: "1.0.0",
      stateContract: "1.0.0",
      pluginVersion: YODA_VERSION,
      hostContract: "1.0.0",
      language: "pt-BR",
      policyMode: "strict",
      managedState: {
        directory: ".brain",
        eventLog: "events.jsonl",
        snapshots: false,
      },
    });
    expect(
      registry.validate({
        id: "state.project-config",
        version: "1.0.0",
        value: config,
        structuralReasonCode: "guard.config_corrupt",
      }).kind,
    ).toBe("valid");
  });

  it("records the policy mode the answers chose in the guardrails", () => {
    const guardrails: unknown = JSON.parse(
      contentAt(
        skeletonEffects(answers({ policyMode: "strict" }), nodeProject),
        ".brain/guardrails.json",
      ),
    );

    expect(guardrails).toMatchObject({ policyMode: "strict" });
  });

  it("records the detected stack and the evidence that decided it", () => {
    const profile = contentAt(
      skeletonEffects(
        answers(),
        profileStack({ rootEntries: ["go.mod", "package.json"] }),
      ),
      ".brain/01-architecture/stack-profile.md",
    );

    // A profile that names a stack without naming why is a profile nobody can
    // check.
    expect(profile).toContain("| go | `go.mod` |");
    expect(profile).toContain("| node | `package.json` |");
  });

  it("says plainly when no known stack matched", () => {
    const profile = contentAt(
      skeletonEffects(answers(), profileStack({ rootEntries: ["README.md"] })),
      ".brain/01-architecture/stack-profile.md",
    );

    expect(profile).toContain("No known stack matched");
  });

  it("wraps the host instructions in the managed markers", () => {
    const generated = skeletonEffects(answers(), nodeProject);

    for (const path of ["AGENTS.md", "CLAUDE.md"]) {
      const content = contentAt(generated, path);

      // Task 4 replaces what sits between these markers and nothing else, so
      // an instruction file that does not carry them cannot be updated safely.
      expect(content.startsWith(`${MANAGED_SECTION_BEGIN}\n`)).toBe(true);
      expect(content.endsWith(`${MANAGED_SECTION_END}\n`)).toBe(true);
    }
  });

  it("carries the conversation language into the host instructions", () => {
    const generated = skeletonEffects(
      answers({ language: "pt-BR" }),
      nodeProject,
    );

    // The managed content stays in English; the language answer says which
    // language the host converses in.
    expect(contentAt(generated, "CLAUDE.md")).toContain("pt-BR");
    expect(contentAt(generated, "AGENTS.md")).toContain("pt-BR");
  });

  it("names only the destinations of a plan, not its narration", () => {
    // A plan carries emitted output as well as writes, and an emitted line is
    // not a file anybody has to be told was touched.
    expect(
      destinationsOf([
        { kind: "emit", channel: "human", text: "Initializing." },
        { kind: "write_file", path: ".brain/config.json", content: "{}\n" },
      ]),
    ).toEqual([".brain/config.json"]);
  });

  it("gives every generated file a body a reader can act on", () => {
    const generated = skeletonEffects(answers(), nodeProject);
    const empty = generated
      .filter(
        (effect) => effect.kind === "write_file" && effect.content.length === 0,
      )
      .map((effect) => (effect.kind === "write_file" ? effect.path : ""));

    // The append-only records and the directory keeper start empty on purpose;
    // everything else says what it is for.
    expect(empty).toEqual([
      ".brain/01-architecture/adr/.gitkeep",
      ".brain/02-features/active",
      ".brain/03-memory/decisions.log",
      ".brain/03-memory/task_log.jsonl",
    ]);
  });
});
