import type { LanguagePolicyV1 } from "@kratos/contracts";

import type { ProjectProfileLeaf, ResolvedProjectProfile } from "./profile.js";
import type { StackProfile } from "./stack.js";

const lines = (...content: readonly string[]): string =>
  `${content.join("\n")}\n`;

/** Render the authoritative project profile without observing or executing it. */
export function renderStackProfile(
  stack: StackProfile,
  projectProfile: ResolvedProjectProfile,
  languagePolicy: LanguagePolicyV1,
): string {
  return lines(
    "# Stack profile",
    "",
    "> Generated by `kratos init` from typed initialization answers and root-entry evidence.",
    "> Manual edits are not authoritative and will be overwritten. Change the typed initialization answers and rerun `kratos init`.",
    "",
    "## Detected stacks",
    "",
    ...renderStacks(stack),
    "",
    "## Commands",
    "",
    "| Command | Value |",
    "| --- | --- |",
    `| Test | ${renderLeaf(projectProfile.commands.test, "projectProfile.commands.test")} |`,
    `| Lint | ${renderLeaf(projectProfile.commands.lint, "projectProfile.commands.lint")} |`,
    `| Build | ${renderLeaf(projectProfile.commands.build, "projectProfile.commands.build")} |`,
    `| Run | ${renderLeaf(projectProfile.commands.run, "projectProfile.commands.run")} |`,
    "",
    "## Paths",
    "",
    "| Path group | Value |",
    "| --- | --- |",
    `| Source | ${renderLeaf(projectProfile.paths.source, "projectProfile.paths.source")} |`,
    `| Tests | ${renderLeaf(projectProfile.paths.tests, "projectProfile.paths.tests")} |`,
    `| Configuration | ${renderLeaf(projectProfile.paths.configuration, "projectProfile.paths.configuration")} |`,
    "",
    "## Conventions",
    "",
    "| Convention | Value |",
    "| --- | --- |",
    `| Directory layout | ${renderLeaf(projectProfile.conventions.directoryLayout, "projectProfile.conventions.directoryLayout")} |`,
    `| Naming | ${renderLeaf(projectProfile.conventions.naming, "projectProfile.conventions.naming")} |`,
    `| Implementation languages | ${renderLeaf(projectProfile.conventions.implementationLanguages, "projectProfile.conventions.implementationLanguages")} |`,
    "",
    "## Language policy",
    "",
    "| Artifact | Language |",
    "| --- | --- |",
    `| Conversation | ${code(languagePolicy.conversation)} |`,
    `| Documentation | ${code(languagePolicy.documentation)} |`,
    `| Comments | ${code(languagePolicy.comments)} |`,
    `| Identifiers | ${code(languagePolicy.identifiers)} |`,
    `| Commits | ${code(languagePolicy.commits)} |`,
    `| Preserve conventions | ${code(String(languagePolicy.preserveConventions))} |`,
    `| Enforcement | ${code(languagePolicy.enforcement)} |`,
  );
}

function renderStacks(stack: StackProfile): readonly string[] {
  if (stack.unrecognized) {
    return [
      "No known stack matched this project root. Detection is offline and limited to root entry names.",
    ];
  }
  return [
    "| Stack | Evidence |",
    "| --- | --- |",
    ...stack.stacks.map(
      ({ id, evidence }) => `| ${escape(id)} | ${code(evidence)} |`,
    ),
  ];
}

function renderLeaf<T>(leaf: ProjectProfileLeaf<T>, key: string): string {
  if (leaf.status === "unresolved") return `\`<UNRESOLVED: ${key}>\``;
  if (leaf.status === "not-applicable") {
    return `Not applicable: ${escape(leaf.reason)}`;
  }
  return Array.isArray(leaf.value)
    ? leaf.value.map((value) => code(String(value))).join(", ")
    : code(String(leaf.value));
}

function code(value: string): string {
  return `\`${escape(value)}\``;
}

/** Escape every character that could alter a Markdown table or inline span. */
function escape(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("|", "&#124;")
    .replaceAll("`", "&#96;");
}
