import type { LanguagePolicyV1 } from "@kratos/contracts";

import type { ProjectProfileLeaf, ResolvedProjectProfile } from "./profile.js";
import type { StackProfile } from "./stack.js";

const lines = (...content: readonly string[]): string =>
  `${content.join("\n")}\n`;

/** Render the authoritative project profile without observing or executing it. */
export function renderStackProfile(
  stack: StackProfile,
  projectProfile: ResolvedProjectProfile,
  languagePolicy: LanguagePolicyV1,
): string {
  return lines(
    "# Stack profile",
    "",
    "> Generated by `kratos init` from typed initialization answers and a bounded, name-only scan of the project tree.",
    "> Manual edits are not authoritative and will be overwritten. Change the typed initialization answers and rerun `kratos init`.",
    "",
    ...renderScanNote(stack),
    "## Detected languages",
    "",
    ...renderLanguages(stack),
    "",
    "## Detected toolchains",
    "",
    ...renderStacks(stack),
    "",
    ...renderObserved(stack),
    "## Commands",
    "",
    ...renderCommand(
      "Test",
      projectProfile.commands.test,
      "projectProfile.commands.test",
    ),
    "",
    ...renderCommand(
      "Lint",
      projectProfile.commands.lint,
      "projectProfile.commands.lint",
    ),
    "",
    ...renderCommand(
      "Build",
      projectProfile.commands.build,
      "projectProfile.commands.build",
    ),
    "",
    ...renderCommand(
      "Run",
      projectProfile.commands.run,
      "projectProfile.commands.run",
    ),
    "",
    "## Paths",
    "",
    "| Path group | Value |",
    "| --- | --- |",
    `| Source | ${renderProseLeaf(projectProfile.paths.source, "projectProfile.paths.source")} |`,
    `| Tests | ${renderProseLeaf(projectProfile.paths.tests, "projectProfile.paths.tests")} |`,
    `| Configuration | ${renderProseLeaf(projectProfile.paths.configuration, "projectProfile.paths.configuration")} |`,
    "",
    "## Conventions",
    "",
    "| Convention | Value |",
    "| --- | --- |",
    `| Directory layout | ${renderProseLeaf(projectProfile.conventions.directoryLayout, "projectProfile.conventions.directoryLayout")} |`,
    `| Naming | ${renderProseLeaf(projectProfile.conventions.naming, "projectProfile.conventions.naming")} |`,
    `| Implementation languages | ${renderProseLeaf(projectProfile.conventions.implementationLanguages, "projectProfile.conventions.implementationLanguages")} |`,
    "",
    "## Language policy",
    "",
    "| Artifact | Language |",
    "| --- | --- |",
    `| Conversation | ${code(languagePolicy.conversation)} |`,
    `| Documentation | ${code(languagePolicy.documentation)} |`,
    `| Comments | ${code(languagePolicy.comments)} |`,
    `| Identifiers | ${code(languagePolicy.identifiers)} |`,
    `| Commits | ${code(languagePolicy.commits)} |`,
    `| Preserve conventions | ${code(String(languagePolicy.preserveConventions))} |`,
    `| Enforcement | ${code(languagePolicy.enforcement)} |`,
  );
}

/**
 * The scan says how much of the tree it saw.
 *
 * A partial listing that reads as a complete one is how a reader concludes a
 * language is absent when the walk simply never reached it.
 */
function renderScanNote(stack: StackProfile): readonly string[] {
  if (!stack.partial) return [];
  return [
    "> The scan reached its entry budget, so this profile describes part of the tree rather than all of it.",
    "",
  ];
}

function renderLanguages(stack: StackProfile): readonly string[] {
  if (stack.languages.length === 0) {
    return [
      "No source file carried an extension this census maps to a language.",
    ];
  }
  return [
    "| Language | Files | Evidence |",
    "| --- | --- | --- |",
    ...stack.languages.map(
      ({ id, files, evidence }) =>
        `| ${escape(id)} | ${String(files)} | ${code(evidence)} |`,
    ),
  ];
}

function renderStacks(stack: StackProfile): readonly string[] {
  if (stack.stacks.length === 0) {
    return [
      "No known toolchain marker was found. Detection is offline and reads names, never file contents.",
    ];
  }
  return [
    "| Toolchain | Evidence |",
    "| --- | --- |",
    ...stack.stacks.map(
      ({ id, evidence }) => `| ${escape(id)} | ${code(evidence)} |`,
    ),
  ];
}

/**
 * What the scan saw when neither layer could name it.
 *
 * Silence gives a host nothing to ask about. The extensions and the root
 * entries are concrete enough for the next question to be a real one.
 */
function renderObserved(stack: StackProfile): readonly string[] {
  if (!stack.unrecognized) return [];
  return [
    "## Observed evidence",
    "",
    "The technology was not identified. This is what the scan saw.",
    "",
    `- Source file extensions: ${renderList(
      stack.observed.extensions.map(
        ({ extension, files }) => `${code(extension)} (${String(files)})`,
      ),
    )}`,
    `- Root entries: ${renderList(stack.observed.rootEntries.map((entry) => code(entry)))}`,
    "",
  ];
}

function renderList(items: readonly string[]): string {
  return items.length === 0 ? "none" : items.join(", ");
}

function renderCommand(
  label: string,
  leaf: ProjectProfileLeaf<string>,
  key: string,
): readonly string[] {
  if (leaf.status === "unresolved") {
    return [`### ${label}`, "", `\`<UNRESOLVED: ${key}>\``];
  }
  if (leaf.status === "not-applicable") {
    return [
      `### ${label}`,
      "",
      `Not applicable: ${escapeMarkdownProse(leaf.reason)}`,
    ];
  }
  const fence = "`".repeat(Math.max(3, longestRun(leaf.value, "`") + 1));
  return [`### ${label}`, "", `${fence}text`, leaf.value, fence];
}

function renderProseLeaf<T>(leaf: ProjectProfileLeaf<T>, key: string): string {
  if (leaf.status === "unresolved") return `\`<UNRESOLVED: ${key}>\``;
  if (leaf.status === "not-applicable") {
    return `Not applicable: ${escapeMarkdownProse(leaf.reason)}`;
  }
  return Array.isArray(leaf.value)
    ? leaf.value.map((value) => escapeMarkdownProse(String(value))).join(", ")
    : escapeMarkdownProse(String(leaf.value));
}

function code(value: string): string {
  return `\`${escape(value)}\``;
}

/** Escape every character that could alter a Markdown table or inline span. */
function escape(value: string): string {
  return visiblyEscapeControls(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("|", "&#124;")
    .replaceAll("`", "&#96;");
}

function escapeMarkdownProse(value: string): string {
  return visiblyEscapeControls(value)
    .replaceAll("\\", "\\\\")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("|", "&#124;")
    .replace(/([`*_[\]{}()#+.!~-])/gu, "\\$1");
}

function visiblyEscapeControls(value: string): string {
  let escaped = "";
  for (const character of value) {
    const codePoint = character.codePointAt(0);
    if (
      codePoint === undefined ||
      (codePoint > 31 &&
        codePoint !== 127 &&
        codePoint !== 0x2028 &&
        codePoint !== 0x2029)
    ) {
      escaped += character;
    } else if (character === "\n") {
      escaped += "\\n";
    } else if (character === "\r") {
      escaped += "\\r";
    } else if (character === "\t") {
      escaped += "\\t";
    } else {
      escaped += `\\u${codePoint.toString(16).padStart(4, "0")}`;
    }
  }
  return escaped;
}

function longestRun(value: string, character: string): number {
  let longest = 0;
  let current = 0;
  for (const candidate of value) {
    if (candidate === character) {
      current += 1;
      longest = Math.max(longest, current);
    } else {
      current = 0;
    }
  }
  return longest;
}
